### ISSUE TITLE
Commends 19/20

### ISSUE THREAD

**Issue by sadistic12** [BeepFelix/csgo-commend-bot#156] opened 2019-11-21 17:42 UTC
My commends keep stopping at 19/20 and won't continue forcing me to relaunch? any ideas?

**Comment by BeepFelix** [comment] 2019-11-21 17:42
Show the log output

**Comment by sadistic12** [comment] 2019-11-21 17:43
Where do I locate the log output?

**Comment by BeepFelix** [comment] 2019-11-21 17:44
Its right in front of your eyes when you run it. Its just the text you see.

**Comment by sadistic12** [comment] 2019-11-21 17:45
PS C:\Users\Xavian\Desktop\csgo-commend-bot-master> node index.js
 Checking for new update...
 Up to date!
 Checking protobufs...
 Found protobufs
 Opening database...
 There are a total of 805 operational accounts
 Parsing target account...
 Chunking 20 accounts into groups of 20...
 Parsing server input
 Parsed server input to 85568392920067105
 Logging in on chunk 1/1
 [] Logging into Steam
 [AdhesiveEnergeticMonkey76] Logging into Steam
 [Adventureee1] Logging into Steam
 [AggressiveDemonicGrouse87] Logging into Steam
 [AgreeableRuthlessCrocodile39] Logging into Steam
 [AjarLaboredGaur21] Logging into Steam
 [AlivePoliteDragonfly93] Logging into Steam
 [AliveQuackButterfly76] Logging into Steam
 [AlluringEnchantingGnu85] Logging into Steam
 [AmazingUnaccountableSheep64] Logging into Steam
 [AmbiguousClosedPanther11] Logging into Steam
 [AmbitiousUnrulyEagle18] Logging into Steam
 [AmuckItchySquirrel59] Logging into Steam
 [AmusedPastoralBeaver] Logging into Steam
 [AmusingGorgeousWolverine] Logging into Steam
 [AmusingWaitingElk59] Logging into Steam
 [AncientBrokenHyena83] Logging into Steam
 [AncientHalfMole94] Logging into Steam
 [AnnoyedTerrificGorilla48] Logging into Steam
 [AnnoyingTartFlamingo13] Logging into Steam
 [AncientBrokenHyena83] Logged onto Steam - GC Time: 11/21/2019, 10:44:58 AM
 [AlluringEnchantingGnu85] Logged onto Steam - GC Time: 11/21/2019, 10:44:58 AM
 [AmbitiousUnrulyEagle18] Logged onto Steam - GC Time: 11/21/2019, 10:44:58 AM
 [AgreeableRuthlessCrocodile39] Logged onto Steam - GC Time: 11/21/2019, 10:44:58 AM
 [AjarLaboredGaur21] Logged onto Steam - GC Time: 11/21/2019, 10:44:58 AM
 [Adventureee1] Logged onto Steam - GC Time: 11/21/2019, 10:44:58 AM
 [AdhesiveEnergeticMonkey76] Logged onto Steam - GC Time: 11/21/2019, 10:44:58 AM
 [AncientBrokenHyena83] Successfully sent a commend with response code 1 - Remaining Commends: 2 (1/20)
 [AnnoyedTerrificGorilla48] Logged onto Steam - GC Time: 11/21/2019, 10:44:58 AM
 [AlluringEnchantingGnu85] Successfully sent a commend with response code 1 - Remaining Commends: 2 (2/20)
 [AggressiveDemonicGrouse87] Logged onto Steam - GC Time: 11/21/2019, 10:44:59 AM
 [AmbitiousUnrulyEagle18] Successfully sent a commend with response code 1 - Remaining Commends: 2 (3/20)
 [AliveQuackButterfly76] Logged onto Steam - GC Time: 11/21/2019, 10:44:59 AM
 [AmusedPastoralBeaver] Logged onto Steam - GC Time: 11/21/2019, 10:44:59 AM
 [AgreeableRuthlessCrocodile39] Successfully sent a commend with response code 1 - Remaining Commends: 2 (4/20)
 [AjarLaboredGaur21] Successfully sent a commend with response code 1 - Remaining Commends: 2 (5/20)
 [AmuckItchySquirrel59] Logged onto Steam - GC Time: 11/21/2019, 10:44:59 AM
 [AmusingWaitingElk59] Logged onto Steam - GC Time: 11/21/2019, 10:44:59 AM
 [AnnoyingTartFlamingo13] Logged onto Steam - GC Time: 11/21/2019, 10:44:59 AM
 [AlivePoliteDragonfly93] Logged onto Steam - GC Time: 11/21/2019, 10:44:59 AM
 [AmazingUnaccountableSheep64] Logged onto Steam - GC Time: 11/21/2019, 10:44:59 AM
 [AmbiguousClosedPanther11] Logged onto Steam - GC Time: 11/21/2019, 10:45:00 AM
 [AncientHalfMole94] Logged onto Steam - GC Time: 11/21/2019, 10:44:59 AM
 [AmusingGorgeousWolverine] Logged onto Steam - GC Time: 11/21/2019, 10:45:00 AM
 [Adventureee1] Successfully sent a commend with response code 1 - Remaining Commends: 2 (6/20)
 [AdhesiveEnergeticMonkey76] Successfully sent a commend with response code 1 - Remaining Commends: 2 (7/20)
 [AnnoyedTerrificGorilla48] Successfully sent a commend with response code 1 - Remaining Commends: 2 (8/20)
 [AggressiveDemonicGrouse87] Successfully sent a commend with response code 1 - Remaining Commends: 2 (9/20)
 [AnnoyingTartFlamingo13] Successfully sent a commend with response code 1 - Remaining Commends: 2 (10/20)
 [AliveQuackButterfly76] Successfully sent a commend with response code 1 - Remaining Commends: 2 (11/20)
 [AlivePoliteDragonfly93] Successfully sent a commend with response code 1 - Remaining Commends: 2 (12/20)
 [AmuckItchySquirrel59] Successfully sent a commend with response code 1 - Remaining Commends: 2 (13/20)
 [AmusingGorgeousWolverine] Successfully sent a commend with response code 1 - Remaining Commends: 2 (14/20)
 [AmusingWaitingElk59] Successfully sent a commend with response code 1 - Remaining Commends: 2 (15/20)
 [AncientHalfMole94] Successfully sent a commend with response code 1 - Remaining Commends: 2 (16/20)
 [AmbiguousClosedPanther11] Successfully sent a commend with response code 1 - Remaining Commends: 2 (17/20)
 [AmusedPastoralBeaver] Successfully sent a commend with response code 1 - Remaining Commends: 2 (18/20)
 [AmazingUnaccountableSheep64] Successfully sent a commend with response code 1 - Remaining Commends: 2 (19/20)

**Comment by BeepFelix** [comment] 2019-11-21 17:46
So no error, just does nothing? How long did you try waiting?

**Comment by sadistic12** [comment] 2019-11-21 17:47
I have waited 10 plus minutes before and nothing, it just stops and wont finish no idea. I updated and everything.

**Comment by BeepFelix** [comment] 2019-11-21 17:49
I don't know why this happens. I have no idea.

**Comment by sadistic12** [comment] 2019-11-21 17:49
Should I try reinstalling or?

**Comment by BeepFelix** [comment] 2019-11-21 17:51
Nah, you can try just simply lowering the `perChunk` amount to like 15 or 19. I doubt resetting would change anything at all.

**Comment by sadistic12** [comment] 2019-11-21 17:53
just tried what you said and its now stopping at 18/19, so confused haha

**Comment by BeepFelix** [comment] 2019-11-21 17:54
That doesn't make any sense, I have no idea what the cause of this could be.

**Comment by dasyah** [comment] 2019-12-04 03:55
I have same problem,I guess only me have that

**Comment by BeepFelix** [comment] 2019-12-07 06:53
Is this still an ongoing issue?

**Comment by MrLolik** [comment] 2019-12-07 13:58
> вход сервера Синтаксического
> вход сервера Parsed к 85568392920067105
> регистрации на куске 1 / 1
**> [] Вход в Steam**
> [AdhesiveEnergeticMonkey76] Вход в Steam
> [Adventureee1] Вход в Steam
> [AggressiveDemonicGrouse87] Вход в Steam
I think first account in "accounts.sqlite" is NULL

**Comment by BeepFelix** [comment] 2019-12-07 14:07
That's true. Its most likely the cause for this

**Comment by BeepFelix** [comment] 2019-12-08 00:24
I will not add an extra option to fix this as it should never actually happen. Download [SQLite Browser](), open the `accounts.sqlite` file with it then navigate to the `Execute SQL` tab and run `DELETE FROM accounts WHERE username = NULL OR password = NULL OR length(password) <= 0;` this should delete all accounts which might be the cause of this issue.

I will close this issue, if you continue to experience problem please open a new issue.

**Closed by BeepFelix** 2019-12-08 00:24 UTC
