### ISSUE TITLE
Constant timeouts

### ISSUE THREAD

**Issue by dwnhauhdwnuhd** [BeepFelix/csgo-commend-bot#160] opened 2019-11-23 21:57 UTC
So soon as i start commending someone, i get red and green error saying something about commending, I dont know  how to fix this.

**Comment by BeepFelix** [comment] 2019-11-23 21:58
Show the error.

**Comment by dwnhauhdwnuhd** [comment] 2019-11-23 21:59
https://gyazo.com/3a06249cb47531fa94de946c635adbe3

**Comment by BeepFelix** [comment] 2019-11-23 22:00
And how does your config look like?

**Comment by dwnhauhdwnuhd** [comment] 2019-11-23 22:02
https://gyazo.com/dbde02b058aed2b439651250914ae0e9

**Comment by BeepFelix** [comment] 2019-11-23 22:04
Your cooldown is *very* low, its likely the same bots are being used which are currently on cooldown and unable to commend and other than that these are possible reasons for your error too: https://github.com/BeepFelix/csgo-commend-bot/issues/149#issuecomment-554678453

**Comment by dwnhauhdwnuhd** [comment] 2019-11-23 22:05
I havnt used this commend bot in weeks, that cant be it.

**Comment by BeepFelix** [comment] 2019-11-23 22:07
Other than the reasons listed I don't know what could be the reason. Other than that this is basically a duplicate of #149

**Closed by BeepFelix** 2019-11-23 22:07 UTC
