### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by Werikson1** [BeepFelix/csgo-commend-bot#57] opened 2019-05-28 05:10 UTC
![Logo](https://user-images.githubusercontent.com/49258737/58452436-b7288000-80ed-11e9-81e1-811a3138a85e.png)

**Comment by BeepFelix** [comment] 2019-05-28 05:11
Stop playing any games on the acacount you are trying to log into.

**Comment by Werikson1** [comment] 2019-05-28 05:18
![Logo](https://user-images.githubusercontent.com/49258737/58452734-c956ee00-80ee-11e9-8bca-6e22eb5ce82d.png)

YEAh ... but

**Comment by BeepFelix** [comment] 2019-05-28 05:18
You didn't follow the install instructions correctly. You either ignored Step 2 & 3 or did them wrong.

**Comment by 0XXXPA** [comment] 2019-05-28 05:21
> You didn't follow the install instructions correctly. You either ignored Step 2 & 3 or did them wrong.

don't want to create a new thread, but I'm interested in 
will there be a fix to the fact that only 20 accounts commend ?

**Comment by BeepFelix** [comment] 2019-05-28 05:23
> > You didn't follow the install instructions correctly. You either ignored Step 2 & 3 or did them wrong.
> 
> don't want to create a new thread, but I'm interested in
> will there be a fix to the fact that only 20 accounts commend ?

I don't know why it doesn't work. Restarting the script seems to let you do 20 more. The issue is that I literally do that with my child-processes. The target account process gets rebooted and all the bots-processes too... yet it doesn't work? I am unsure why.

**Comment by 0XXXPA** [comment] 2019-05-28 05:28
> I don't know why it doesn't work. Restarting the script seems to let you do 20 more. The issue is that I literally do that with my child-processes. The target account process gets rebooted and all the bots-processes too... yet it doesn't work? I am unsure why.

when I restart the script at 70% it doesn't work either

**Comment by BeepFelix** [comment] 2019-05-28 05:44
Put `betweenChunks` to `240000` and it will work pretty fine. This issue seems to be resolved I think so I will just close it.

In the future for everyone else, just following the install instructions.. come on, its not hard. And no you don't have to extract anything, just put the entire protobufs with all sub folders into it and it will work.

**Closed by BeepFelix** 2019-05-28 05:44 UTC
